<?php
$radar_msg = [
    [
        "sign"=> "copy",
        "type"=> 8,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "咨询",
        "item"=> "产品",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],

    [
        "sign"=> "view",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "商城列表",
        "show_count"=> 1,
        "table_name"=> "longbing_card_shop_type",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机，主动提供细致的商品讲解将大大有利于成交",
        "operation"=> "正在查看",
        "item"=> "商品",
        "show_count"=> 0,
        "table_name"=> "longbing_card_goods",
        "field"=> "name",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 11,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "商品分类列表",
        "show_count"=> 1,
        "table_name"=> "longbing_card_shop_type",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],

    [
        "sign"=> "view",
        "type"=> 19,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "订单商品已发货，系统订单号为：",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 20,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "自提商品已提货",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 21,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请等待管理员审核并注意查收",
        "operation"=> "已申请退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 22,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "已取消申请退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 23,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "管理员拒绝退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "view",
        "type"=> 24,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请注意查收",
        "operation"=> "退款成功",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "order",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在订单中心查看详情",
        "operation"=> "已购买商品",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "order",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在订单中心查看详情",
        "operation"=> "已参与拼团",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "order",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在预约订单中心查看详情",
        "operation"=> "预约了",
        "item"=> "服务",
        "show_count"=> 0,
        "table_name"=> "lb_appoint_record",
        "field"=> "name,phone,project_id,start_time,remark",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ],


];

return $radar_msg;
