<?php

$radar_msg_data = [
    [
        "sign"=> "praises",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "查看",
        "item"=> "名片",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "对你已建立信任，保持联系持续跟进",
        "operation"=> "将",
        "item"=> "手机号码存入了手机通讯录",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "咨询意向强烈，及时联系确保沟通顺畅",
        "operation"=> "拨打",
        "item"=> "手机号",
        "show_count"=> 0,
        "table_name"=> "longbing_card_user_info",
        "field"=> "phone",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请随时保持电话畅通",
        "operation"=> "拨打",
        "item"=> "公司电话",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 4,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "客户请随时可能加你微信",
        "operation"=> "复制了",
        "item"=> "微信",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 5,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "可能随时邮寄文件给你，请注意查收",
        "operation"=> "复制了",
        "item"=> "邮箱",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 6,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "复制",
        "item"=> "公司名称",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 7,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "对你的公司非常感兴趣",
        "operation"=> "查看了",
        "item"=> "公司地址",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 8,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "咨询",
        "item"=> "产品",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 9,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "播放",
        "item"=> "语音",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 10,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "保存了",
        "item"=> "名片海报",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "copy",
        "type"=> 11,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请随时保持电话畅通",
        "operation"=> "拨打",
        "item"=> "400热线",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "商城列表",
        "show_count"=> 1,
        "table_name"=> "longbing_card_shop_type",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机，主动提供细致的商品讲解将大大有利于成交",
        "operation"=> "正在查看你的",
        "item"=> "商品",
        "show_count"=> 0,
        "table_name"=> "longbing_card_goods",
        "field"=> "name",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "看来TA对公司动态感兴趣",
        "operation"=> "浏览",
        "item"=> "动态列表",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 4,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "点赞",
        "item"=> "动态",
        "show_count"=> 0,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 5,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "评论了",
        "item"=> "动态",
        "show_count"=> 0,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 6,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "查看了",
        "item"=> "企业官网",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 7,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "正在查看",
        "item"=> "动态",
        "show_count"=> 0,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 8,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "正在查看",
        "item"=> "动态视频",
        "show_count"=> 0,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 9,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "正在查看",
        "item"=> "动态外链",
        "show_count"=> 1,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 10,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "通过动态列表跳转小程序",
        "item"=> "",
        "show_count"=> 1,
        "table_name"=> "longbing_card_timeline",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 11,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "商品分类列表",
        "show_count"=> 1,
        "table_name"=> "longbing_card_shop_type",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 12,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快展开跟进",
        "operation"=> "正在阅读",
        "item"=> "文章",
        "show_count"=> 0,
        "table_name"=> "lb_marketing_article_v2",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 13,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "分享了",
        "item"=> "文章",
        "show_count"=> 0,
        "table_name"=> "lb_marketing_article_v2",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 14,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "保存",
        "item"=> "文章海报",
        "show_count"=> 0,
        "table_name"=> "lb_marketing_article_v2",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 15,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "查看了",
        "item"=> "预约",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 16,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "预约栏目",
        "show_count"=> 1,
        "table_name"=> "lb_appoint_classify",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 17,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "预约活动",
        "operation"=> "正在查看",
        "item"=> "预约",
        "show_count"=> 0,
        "table_name"=> "lb_appoint_project",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 18,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快处理",
        "operation"=> "在官网留言",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_form",
        "field"=> "name,phone,content",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 19,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "订单商品已发货，系统订单号为：",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 20,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "自提商品已提货",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 21,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请等待管理员审核并注意查收",
        "operation"=> "已申请退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 22,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "已取消申请退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 23,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请前往订单中心查看详情",
        "operation"=> "管理员拒绝退款",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 24,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请注意查收",
        "operation"=> "退款成功",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 25,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "查看了",
        "item"=> "活动",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 26,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "浏览",
        "item"=> "活动报名分类列表",
        "show_count"=> 1,
        "table_name"=> "lb_activity_classify",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 27,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "正在查看",
        "item"=> "活动",
        "show_count"=> 0,
        "table_name"=> "lb_activity_activity",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 28,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在活动开始前提醒客户",
        "operation"=> "已参加了活动",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "lb_activity_activity",
        "field"=> "title",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 29,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "正在查看",
        "item"=> "房源信息",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "view",
        "type"=> 30,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "查看了",
        "item"=> "房源",
        "show_count"=> 0,
        "table_name"=> "longbing_card_house",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "语音点赞",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "查看",
        "item"=> "名片",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "Ta给你点赞了",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 4,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "分享了",
        "item"=> "名片",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 5,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "咨询",
        "item"=> "房源信息",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 6,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "收藏了",
        "item"=> "房源",
        "show_count"=> 0,
        "table_name"=> "longbing_card_house",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 7,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "电话咨询了",
        "item"=> "房源",
        "show_count"=> 0,
        "table_name"=> "longbing_card_house",
        "field"=> "title",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "praise",
        "type"=> 8,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请提前联系客户",
        "operation"=> "预约查看",
        "item"=> "房源",
        "show_count"=> 0,
        "table_name"=> "longbing_card_house",
        "field"=> "title",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "order",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在订单中心查看详情",
        "operation"=> "已购买商品",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "order",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在订单中心查看详情",
        "operation"=> "已参与拼团",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "longbing_card_shop_order",
        "field"=> "out_trade_no",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "order",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请在预约订单中心查看详情",
        "operation"=> "预约了",
        "item"=> "服务",
        "show_count"=> 0,
        "table_name"=> "lb_appoint_record",
        "field"=> "name,phone,project_id,start_time,remark",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ], 
    [
        "sign"=> "qr",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "正在使用扫码支付",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "lb_pay_qr_record",
        "field"=> "money",
        "send"=> 2,
        "uniacid"=> 2,
        "status"=> 1
    ],
];