<?php
$radar_msg = [
    [
        "sign"=> "praise",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "查看",
        "item"=> "名片",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "对你已建立信任，保持联系持续跟进",
        "operation"=> "将",
        "item"=> "手机号码存入了手机通讯录",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 2,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "咨询意向强烈，及时联系确保沟通顺畅",
        "operation"=> "拨打",
        "item"=> "手机号",
        "show_count"=> 0,
        "table_name"=> "longbing_card_user_info",
        "field"=> "phone",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请随时保持电话畅通",
        "operation"=> "拨打",
        "item"=> "公司电话",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 4,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "客户请随时可能加你微信",
        "operation"=> "复制了",
        "item"=> "微信",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 5,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "可能随时邮寄文件给你，请注意查收",
        "operation"=> "复制了",
        "item"=> "邮箱",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 6,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "复制",
        "item"=> "公司名称",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 7,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "对你的公司非常感兴趣",
        "operation"=> "查看了",
        "item"=> "公司地址",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 9,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请及时留意雷达动态",
        "operation"=> "播放",
        "item"=> "语音",
        "show_count"=> 1,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 10,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "保存了",
        "item"=> "名片海报",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "copy",
        "type"=> 11,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请随时保持电话畅通",
        "operation"=> "拨打",
        "item"=> "400热线",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "praise",
        "type"=> 1,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "请尽快把握商机",
        "operation"=> "语音点赞",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "praise",
        "type"=> 3,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "",
        "operation"=> "Ta给你点赞了",
        "item"=> "",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],
    [
        "sign"=> "praise",
        "type"=> 4,
        "max"=> 0,
        "pid"=> 0,
        "msg"=> "正在帮你裂变人脉，请及时留意雷达动态（快去表达一下你的感谢）",
        "operation"=> "分享了",
        "item"=> "名片",
        "show_count"=> 0,
        "table_name"=> "",
        "field"=> "",
        "send"=> 1,
        "uniacid"=> 2,
        "status"=> 1
    ],

];

return $radar_msg;
